resilience4j:
  retry:
    instances:
      myRetry1:
        maxAttempts: 3
        waitDuration: 20
        retryEnable: true
        retryExceptions:
          - java.lang.Exception
          - com.exampledev.demodev.example.exceptions.EmptyResponseException
          - org.springframework.web.client.HttpServerErrorException

      myRetry2:
        maxAttempts: 5
        waitDuration: 10
        retryEnable: false
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException